# Generated by Django 3.1.5 on 2021-02-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0002_auto_20210208_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
