# Generated by Django 3.1.5 on 2021-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0003_productimage_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
