# Generated by Django 3.1.5 on 2021-02-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0004_auto_20210208_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, max_length=100),
        ),
    ]
