# Generated by Django 3.1.5 on 2021-02-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0005_auto_20210209_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, max_length=100),
        ),
    ]
