# Generated by Django 3.1.5 on 2021-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0016_auto_20210216_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('color', 'color'), ('size', 'size')], default='size', max_length=120),
        ),
    ]
