# Generated by Django 3.1.5 on 2021-02-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0018_auto_20210221_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa fa-tshirt', max_length=50),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('color', 'color'), ('size', 'size')], default='size', max_length=120),
        ),
    ]
