# Generated by Django 3.1.5 on 2021-02-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0020_auto_20210221_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MStore.productmodel'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('size', 'size'), ('color', 'color')], default='size', max_length=120),
        ),
    ]
