# Generated by Django 3.1.5 on 2021-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0022_auto_20210222_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
