# Generated by Django 3.1.5 on 2021-02-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0025_auto_20210223_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('size', 'size'), ('color', 'color')], default='size', max_length=120),
        ),
    ]
