# Generated by Django 3.1.5 on 2021-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0027_auto_20210225_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('size', 'size'), ('color', 'color')], default='size', max_length=120),
        ),
    ]
