# Generated by Django 3.1.5 on 2021-02-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0029_auto_20210226_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('number', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('percentage', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('color', 'color'), ('size', 'size')], default='size', max_length=120),
        ),
    ]
