# Generated by Django 3.1.5 on 2021-02-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0030_auto_20210226_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupontotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000, max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
