# Generated by Django 3.1.5 on 2021-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0031_auto_20210226_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='couponapplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('color', 'color'), ('size', 'size')], default='size', max_length=120),
        ),
    ]
