# Generated by Django 3.1.5 on 2021-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0032_auto_20210227_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
