# Generated by Django 3.1.5 on 2021-03-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0037_auto_20210301_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='uploaded',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('package', 'package'), ('size', 'size')], default='size', max_length=120),
        ),
    ]
