# Generated by Django 3.1.5 on 2021-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0041_auto_20210302_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
