# Generated by Django 3.1.5 on 2021-03-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MStore', '0042_auto_20210302_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='MStore.tags'),
        ),
    ]
