# Generated by Django 3.1.5 on 2021-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_sliderhome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhome',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
