# Generated by Django 3.1.5 on 2021-02-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210221_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderhome',
            name='button_link',
        ),
        migrations.AddField(
            model_name='sliderhome',
            name='url_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
