# Generated by Django 3.1.5 on 2021-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='0120000000000', max_length=20)),
                ('email', models.EmailField(max_length=400)),
                ('address', models.TextField(max_length=1000)),
            ],
        ),
    ]
