# Generated by Django 3.1.5 on 2021-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0003_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='link',
            field=models.CharField(default='xyz', max_length=600),
        ),
    ]
