# Generated by Django 3.1.5 on 2021-03-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0004_copyright_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', models.TextField(max_length=2000)),
                ('privacy_policy', models.TextField(max_length=2000)),
                ('terms_conditions', models.TextField(max_length=2000)),
                ('payment_policy', models.TextField(max_length=2000)),
                ('shipping_policy', models.TextField(max_length=2000)),
                ('return_policy', models.TextField(max_length=2000)),
            ],
        ),
    ]
