# Generated by Django 3.1.5 on 2021-02-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MStore', '0013_auto_20210215_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='abcde', max_length=120, unique=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Abandoned', 'Abandoned'), ('OnDelivery', 'OnDelivery'), ('Delivered', 'Delivered')], default='Received', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MStore.cart')),
            ],
        ),
    ]
