# Generated by Django 3.1.5 on 2021-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_userdefaultaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
