# Generated by Django 3.1.5 on 2021-03-01 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_useraddress_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdefaultaddress',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='userdefaultaddress',
            name='shipping',
        ),
        migrations.AddField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address_billing_default', to='orders.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address_shipping_default', to='orders.useraddress'),
        ),
    ]
